# Start with a Python base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install Python dependencies
# COPY requirements.txt /app/
# RUN pip install --no-cache-dir -r requirements.txt

# Copy the Streamlit script into the container
COPY . /app/

# Expose the port Streamlit runs on
EXPOSE 8501

# Command to run on container start
CMD ["streamlit", "run", "serve.py"]